config/routes.rb
Bbfapp::Application.routes.draw do
  root :to => redirect('/beer_bars')
    resources :beer_bars

end

app/models/beer_bar.rb
class BeerBar < ActiveRecord::Base
	validates_presence_of :name, :state, :website
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/beer_bars_controller.rb
class BeerBarsController < ApplicationController
  before_action :set_beer_bar, only: [:show, :edit, :update, :destroy]

  # GET /beer_bars
  # GET /beer_bars.json
  def index
    @beer_bars = BeerBar.all
  end

  # GET /beer_bars/1
  # GET /beer_bars/1.json
  def show
  end

  # GET /beer_bars/new
  def new
    @beer_bar = BeerBar.new
  end

  # GET /beer_bars/1/edit
  def edit
  end

  # POST /beer_bars
  # POST /beer_bars.json
  def create
    @beer_bar = BeerBar.new(beer_bar_params)

    respond_to do |format|
      if @beer_bar.save
        format.html { redirect_to @beer_bar, notice: 'Beer bar was successfully created.' }
        format.json { render action: 'show', status: :created, location: @beer_bar }
      else
        format.html { render action: 'new' }
        format.json { render json: @beer_bar.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /beer_bars/1
  # PATCH/PUT /beer_bars/1.json
  def update
    respond_to do |format|
      if @beer_bar.update(beer_bar_params)
        format.html { redirect_to @beer_bar, notice: 'Beer bar was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @beer_bar.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /beer_bars/1
  # DELETE /beer_bars/1.json
  def destroy
    @beer_bar.destroy
    respond_to do |format|
      format.html { redirect_to beer_bars_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_beer_bar
      @beer_bar = BeerBar.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def beer_bar_params
      params.require(:beer_bar).permit(:bb_id, :name, :address, :city, :state, :zipcode, :description, :website, :datecreated)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/beer_bars_helper.rb
module BeerBarsHelper
end

app/views/beer_bars/_form.html.erb
<%= simple_form_for(@beer_bar) do |f| %>
  <%= f.input :name %>
  <%= f.input :address %>
  <%= f.input :city %>
  <%= f.input :state %>
  <%= f.input :zipcode %>
  <%= f.input :description %>
  <%= f.input :website %>
  <%= f.input :datecreated %>
  <%= f.button :submit %>  
<% end %>

app/views/beer_bars/edit.html.erb
<h1>Editing beer_bar</h1>

<%= render 'form' %>

<%= link_to 'Show', @beer_bar %> |
<%= link_to 'Back', beer_bars_path %>

app/views/beer_bars/index.html.erb
<h1>Listing beer_bars</h1>


  <% @beer_bars.each do |beer_bar| %>
    <strong><%= link_to beer_bar.name, beer_bar %></strong><br>
    <%= beer_bar.city %><br>
    <%= beer_bar.state %><br>
    <%= beer_bar.website %><br>
    <!-- <%= link_to 'Show', beer_bar %>
    <%= link_to 'Edit', edit_beer_bar_path(beer_bar) %>
    <%= link_to 'Destroy', beer_bar, method: :delete, data: { confirm: 'Are you sure?' } %> -->
    <br><br>
  <% end %>

<br>

<%= link_to 'New Beer bar', new_beer_bar_path %>

app/views/beer_bars/new.html.erb
<h1>New Beer Bar</h1>

<%= render 'form' %>

<%= link_to 'Back', beer_bars_path %>

app/views/beer_bars/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <%= @beer_bar.name %>
</p>

<p>
  <%= @beer_bar.address %>
</p>

<p>
  <%= @beer_bar.city %>
</p>

<p>
  <%= @beer_bar.state %>
</p>

<p>
  <%= @beer_bar.zipcode %>
</p>

<p>
  <strong>Description:</strong>
  <%= @beer_bar.description %>
</p>

<p>
  <strong>Website:</strong>
  <%= @beer_bar.website %>
</p>

<%= link_to 'Edit', edit_beer_bar_path(@beer_bar) %> |
<%= link_to 'Back', beer_bars_path %>

app/views/layouts/_messages.html.erb
<%# Rails flash messages styled for Bootstrap 3.0 %>
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <div class="alert alert-<%= name == :notice ? "success" : "danger" %>">
      <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
      <%= content_tag :div, msg, :id => "flash_#{name}" %>
    </div>
  <% end %>
<% end %>

app/views/layouts/_navigation.html.erb
<%# navigation styled for Bootstrap 3.0 %>
<nav class="navbar navbar-inverse navbar-fixed-top">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to 'Home', root_path, class: 'navbar-brand' %>
    </div>
    <div class="collapse navbar-collapse">
      <ul class="nav navbar-nav">
        <%= render 'layouts/navigation_links' %>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/_navigation_links.html.erb
<%# add navigation links to this file %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Bbfapp" %></title>
    <meta name="description" content="<%= content_for?(:description) ? yield(:description) : "Bbfapp" %>">
    <%= stylesheet_link_tag "application", media: "all", "data-turbolinks-track" => true %>
    <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
    <%= csrf_meta_tags %>
  </head>
  <body>
    <header>
      <%= render 'layouts/navigation' %>
    </header>
    <main role="main">
       <%= render 'layouts/messages' %>
       <%= yield %>
    </main>
  </body>
</html>